/*
 * Global Default Offers API
 * This is the Offers API providing the default offers for partners across various applications in Acquisition portfolio
 *
 * OpenAPI spec version: 1.0
 * Contact: DAPXServices@aexp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.americanexpress.sdk.models.default_offers;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Holds fee information
 */
@ApiModel(description = "Holds fee information")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-28T10:45:02.623-04:00[America/New_York]")
public class Fee {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_DISPLAY_TEXT = "display_text";
  @SerializedName(SERIALIZED_NAME_DISPLAY_TEXT)
  private String displayText;

  public Fee name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Represents type of fee,INTORDUCTORY_ANNUAL_FEE,ANNUAL_FEE,NO_ANNUAL_FEE
   * @return name
  **/
  @ApiModelProperty(value = "Represents type of fee,INTORDUCTORY_ANNUAL_FEE,ANNUAL_FEE,NO_ANNUAL_FEE")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Fee type(String type) {
    this.type = type;
    return this;
  }

   /**
   * It specifies the representation for example FIXED,PERCENTAGE
   * @return type
  **/
  @ApiModelProperty(value = "It specifies the representation for example FIXED,PERCENTAGE")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Fee value(String value) {
    this.value = value;
    return this;
  }

   /**
   * fee  amount ex. 95
   * @return value
  **/
  @ApiModelProperty(value = "fee  amount ex. 95")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public Fee currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * type of currency like USD , RUPEE
   * @return currency
  **/
  @ApiModelProperty(value = "type of currency like USD , RUPEE")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Fee displayText(String displayText) {
    this.displayText = displayText;
    return this;
  }

   /**
   * text to be displayed on the page ex. $0 for the first year, then $195
   * @return displayText
  **/
  @ApiModelProperty(value = "text to be displayed on the page ex. $0 for the first year, then $195")
  public String getDisplayText() {
    return displayText;
  }

  public void setDisplayText(String displayText) {
    this.displayText = displayText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fee fee = (Fee) o;
    return Objects.equals(this.name, fee.name) &&
        Objects.equals(this.type, fee.type) &&
        Objects.equals(this.value, fee.value) &&
        Objects.equals(this.currency, fee.currency) &&
        Objects.equals(this.displayText, fee.displayText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, value, currency, displayText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fee {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    displayText: ").append(toIndentedString(displayText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

