/*
 * Global Default Offers API
 * This is the Offers API providing the default offers for partners across various applications in Acquisition portfolio
 *
 * OpenAPI spec version: 1.0
 * Contact: DAPXServices@aexp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.americanexpress.sdk.models.default_offers;

import java.util.Objects;
import java.util.Arrays;
import com.americanexpress.sdk.models.default_offers.ContentGroup;
import com.americanexpress.sdk.models.default_offers.Fee;
import com.americanexpress.sdk.models.default_offers.Rate;
import com.americanexpress.sdk.models.default_offers.Reward;
import com.americanexpress.sdk.models.default_offers.Url;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Offer
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-28T10:45:02.623-04:00[America/New_York]")
public class Offer {
  public static final String SERIALIZED_NAME_ACQUISITION_OFFER_ID = "acquisition_offer_id";
  @SerializedName(SERIALIZED_NAME_ACQUISITION_OFFER_ID)
  private String acquisitionOfferId;

  public static final String SERIALIZED_NAME_LINE_OF_BUSINESS = "line_of_business";
  @SerializedName(SERIALIZED_NAME_LINE_OF_BUSINESS)
  private String lineOfBusiness;

  public static final String SERIALIZED_NAME_PRODUCT_NAME = "product_name";
  @SerializedName(SERIALIZED_NAME_PRODUCT_NAME)
  private String productName;

  public static final String SERIALIZED_NAME_PRODUCT_TYPE = "product_type";
  @SerializedName(SERIALIZED_NAME_PRODUCT_TYPE)
  private String productType;

  public static final String SERIALIZED_NAME_REWARDS = "rewards";
  @SerializedName(SERIALIZED_NAME_REWARDS)
  private List<Reward> rewards = null;

  public static final String SERIALIZED_NAME_URLS = "urls";
  @SerializedName(SERIALIZED_NAME_URLS)
  private List<Url> urls = null;

  public static final String SERIALIZED_NAME_FEES = "fees";
  @SerializedName(SERIALIZED_NAME_FEES)
  private List<Fee> fees = null;

  public static final String SERIALIZED_NAME_RATES = "rates";
  @SerializedName(SERIALIZED_NAME_RATES)
  private List<Rate> rates = null;

  public static final String SERIALIZED_NAME_CONTENT_GROUPS = "content_groups";
  @SerializedName(SERIALIZED_NAME_CONTENT_GROUPS)
  private List<ContentGroup> contentGroups = null;

  public Offer acquisitionOfferId(String acquisitionOfferId) {
    this.acquisitionOfferId = acquisitionOfferId;
    return this;
  }

   /**
   * unique offer identifier
   * @return acquisitionOfferId
  **/
  @ApiModelProperty(value = "unique offer identifier")
  public String getAcquisitionOfferId() {
    return acquisitionOfferId;
  }

  public void setAcquisitionOfferId(String acquisitionOfferId) {
    this.acquisitionOfferId = acquisitionOfferId;
  }

  public Offer lineOfBusiness(String lineOfBusiness) {
    this.lineOfBusiness = lineOfBusiness;
    return this;
  }

   /**
   * Indicate line of business value would be CONSUMER OR SMALL_BUSINESS
   * @return lineOfBusiness
  **/
  @ApiModelProperty(value = "Indicate line of business value would be CONSUMER OR SMALL_BUSINESS")
  public String getLineOfBusiness() {
    return lineOfBusiness;
  }

  public void setLineOfBusiness(String lineOfBusiness) {
    this.lineOfBusiness = lineOfBusiness;
  }

  public Offer productName(String productName) {
    this.productName = productName;
    return this;
  }

   /**
   * name of the product
   * @return productName
  **/
  @ApiModelProperty(value = "name of the product")
  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }

  public Offer productType(String productType) {
    this.productType = productType;
    return this;
  }

   /**
   * type of the product example, CHARGE or LENDING
   * @return productType
  **/
  @ApiModelProperty(value = "type of the product example, CHARGE or LENDING")
  public String getProductType() {
    return productType;
  }

  public void setProductType(String productType) {
    this.productType = productType;
  }

  public Offer rewards(List<Reward> rewards) {
    this.rewards = rewards;
    return this;
  }

  public Offer addRewardsItem(Reward rewardsItem) {
    if (this.rewards == null) {
      this.rewards = new ArrayList<>();
    }
    this.rewards.add(rewardsItem);
    return this;
  }

   /**
   * holds the rewards information
   * @return rewards
  **/
  @Valid
  @ApiModelProperty(value = "holds the rewards information")
  public List<Reward> getRewards() {
    return rewards;
  }

  public void setRewards(List<Reward> rewards) {
    this.rewards = rewards;
  }

  public Offer urls(List<Url> urls) {
    this.urls = urls;
    return this;
  }

  public Offer addUrlsItem(Url urlsItem) {
    if (this.urls == null) {
      this.urls = new ArrayList<>();
    }
    this.urls.add(urlsItem);
    return this;
  }

   /**
   * Get urls
   * @return urls
  **/
  @Valid
  @ApiModelProperty(value = "")
  public List<Url> getUrls() {
    return urls;
  }

  public void setUrls(List<Url> urls) {
    this.urls = urls;
  }

  public Offer fees(List<Fee> fees) {
    this.fees = fees;
    return this;
  }

  public Offer addFeesItem(Fee feesItem) {
    if (this.fees == null) {
      this.fees = new ArrayList<>();
    }
    this.fees.add(feesItem);
    return this;
  }

   /**
   * holds any fee related to product ex,annual fee of the product
   * @return fees
  **/
  @Valid
  @ApiModelProperty(value = "holds any fee related to product ex,annual fee of the product")
  public List<Fee> getFees() {
    return fees;
  }

  public void setFees(List<Fee> fees) {
    this.fees = fees;
  }

  public Offer rates(List<Rate> rates) {
    this.rates = rates;
    return this;
  }

  public Offer addRatesItem(Rate ratesItem) {
    if (this.rates == null) {
      this.rates = new ArrayList<>();
    }
    this.rates.add(ratesItem);
    return this;
  }

   /**
   * holds rates array
   * @return rates
  **/
  @Valid
  @ApiModelProperty(value = "holds rates array")
  public List<Rate> getRates() {
    return rates;
  }

  public void setRates(List<Rate> rates) {
    this.rates = rates;
  }

  public Offer contentGroups(List<ContentGroup> contentGroups) {
    this.contentGroups = contentGroups;
    return this;
  }

  public Offer addContentGroupsItem(ContentGroup contentGroupsItem) {
    if (this.contentGroups == null) {
      this.contentGroups = new ArrayList<>();
    }
    this.contentGroups.add(contentGroupsItem);
    return this;
  }

   /**
   * holds list of content groups with contents related to offer
   * @return contentGroups
  **/
  @Valid
  @ApiModelProperty(value = "holds list of content groups with contents related to offer")
  public List<ContentGroup> getContentGroups() {
    return contentGroups;
  }

  public void setContentGroups(List<ContentGroup> contentGroups) {
    this.contentGroups = contentGroups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Offer offer = (Offer) o;
    return Objects.equals(this.acquisitionOfferId, offer.acquisitionOfferId) &&
        Objects.equals(this.lineOfBusiness, offer.lineOfBusiness) &&
        Objects.equals(this.productName, offer.productName) &&
        Objects.equals(this.productType, offer.productType) &&
        Objects.equals(this.rewards, offer.rewards) &&
        Objects.equals(this.urls, offer.urls) &&
        Objects.equals(this.fees, offer.fees) &&
        Objects.equals(this.rates, offer.rates) &&
        Objects.equals(this.contentGroups, offer.contentGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acquisitionOfferId, lineOfBusiness, productName, productType, rewards, urls, fees, rates, contentGroups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Offer {\n");
    
    sb.append("    acquisitionOfferId: ").append(toIndentedString(acquisitionOfferId)).append("\n");
    sb.append("    lineOfBusiness: ").append(toIndentedString(lineOfBusiness)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    productType: ").append(toIndentedString(productType)).append("\n");
    sb.append("    rewards: ").append(toIndentedString(rewards)).append("\n");
    sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
    sb.append("    fees: ").append(toIndentedString(fees)).append("\n");
    sb.append("    rates: ").append(toIndentedString(rates)).append("\n");
    sb.append("    contentGroups: ").append(toIndentedString(contentGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

