/*
 * Global Default Offers API
 * This is the Offers API providing the default offers for partners across various applications in Acquisition portfolio
 *
 * OpenAPI spec version: 1.0
 * Contact: DAPXServices@aexp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.americanexpress.sdk.models.default_offers;

import java.util.Objects;
import java.util.Arrays;
import com.americanexpress.sdk.models.default_offers.Offer;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * OffersResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-28T10:45:02.623-04:00[America/New_York]")
public class OffersResponse {
  public static final String SERIALIZED_NAME_REFRESH_INTERVAL = "refresh_interval";
  @SerializedName(SERIALIZED_NAME_REFRESH_INTERVAL)
  private String refreshInterval;

  public static final String SERIALIZED_NAME_OFFERS = "offers";
  @SerializedName(SERIALIZED_NAME_OFFERS)
  private List<Offer> offers = null;

  public OffersResponse refreshInterval(String refreshInterval) {
    this.refreshInterval = refreshInterval;
    return this;
  }

   /**
   * Time to live for token in milliseconds; the amount of time a token will remain valid.
   * @return refreshInterval
  **/
  @ApiModelProperty(value = "Time to live for token in milliseconds; the amount of time a token will remain valid.")
  public String getRefreshInterval() {
    return refreshInterval;
  }

  public void setRefreshInterval(String refreshInterval) {
    this.refreshInterval = refreshInterval;
  }

  public OffersResponse offers(List<Offer> offers) {
    this.offers = offers;
    return this;
  }

  public OffersResponse addOffersItem(Offer offersItem) {
    if (this.offers == null) {
      this.offers = new ArrayList<>();
    }
    this.offers.add(offersItem);
    return this;
  }

   /**
   * holds list of offers
   * @return offers
  **/
  @Valid
  @ApiModelProperty(value = "holds list of offers")
  public List<Offer> getOffers() {
    return offers;
  }

  public void setOffers(List<Offer> offers) {
    this.offers = offers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OffersResponse offersResponse = (OffersResponse) o;
    return Objects.equals(this.refreshInterval, offersResponse.refreshInterval) &&
        Objects.equals(this.offers, offersResponse.offers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(refreshInterval, offers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OffersResponse {\n");
    
    sb.append("    refreshInterval: ").append(toIndentedString(refreshInterval)).append("\n");
    sb.append("    offers: ").append(toIndentedString(offers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

