/*
 * Global Default Offers API
 * This is the Offers API providing the default offers for partners across various applications in Acquisition portfolio
 *
 * OpenAPI spec version: 1.0
 * Contact: DAPXServices@aexp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.americanexpress.sdk.models.default_offers;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * This model represents rates information
 */
@ApiModel(description = "This model represents rates information")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-28T10:45:02.623-04:00[America/New_York]")
public class Rate {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_DISPLAY_TEXT = "display_text";
  @SerializedName(SERIALIZED_NAME_DISPLAY_TEXT)
  private String displayText;

  public static final String SERIALIZED_NAME_DURATION = "duration";
  @SerializedName(SERIALIZED_NAME_DURATION)
  private String duration;

  public Rate name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of rates information,ex. INTORDUCTORY_PURCHASE_APR,REGULAR_PURCHASE_APR, INTORDUCTORY_BALANCE_TRANSFER_APR,REGULAR_BALANCE_TRANSFER_APR,CASH_ADVANCE_APR,PENALTY_APR,PRIME_RATE
   * @return name
  **/
  @ApiModelProperty(value = "Name of rates information,ex. INTORDUCTORY_PURCHASE_APR,REGULAR_PURCHASE_APR, INTORDUCTORY_BALANCE_TRANSFER_APR,REGULAR_BALANCE_TRANSFER_APR,CASH_ADVANCE_APR,PENALTY_APR,PRIME_RATE")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Rate value(String value) {
    this.value = value;
    return this;
  }

   /**
   * APR value, ex. 13.5%
   * @return value
  **/
  @ApiModelProperty(value = "APR value, ex. 13.5%")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public Rate displayText(String displayText) {
    this.displayText = displayText;
    return this;
  }

   /**
   * APR text to be displayed on the page ex. 0.0% for 15 months
   * @return displayText
  **/
  @ApiModelProperty(value = "APR text to be displayed on the page ex. 0.0% for 15 months")
  public String getDisplayText() {
    return displayText;
  }

  public void setDisplayText(String displayText) {
    this.displayText = displayText;
  }

  public Rate duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Duration of the APR applicable,ex. 15 months
   * @return duration
  **/
  @ApiModelProperty(value = "Duration of the APR applicable,ex. 15 months")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rate rate = (Rate) o;
    return Objects.equals(this.name, rate.name) &&
        Objects.equals(this.value, rate.value) &&
        Objects.equals(this.displayText, rate.displayText) &&
        Objects.equals(this.duration, rate.duration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value, displayText, duration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rate {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    displayText: ").append(toIndentedString(displayText)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

