/*
 * Global Default Offers API
 * This is the Offers API providing the default offers for partners across various applications in Acquisition portfolio
 *
 * OpenAPI spec version: 1.0
 * Contact: DAPXServices@aexp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.americanexpress.sdk.models.default_offers;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Represents the reward associated with the offer. Can be cashback or loyalty currency.
 */
@ApiModel(description = "Represents the reward associated with the offer. Can be cashback or loyalty currency.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-28T10:45:02.623-04:00[America/New_York]")
public class Reward {
  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private Integer value;

  public Reward currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * type of currency. Possible values: [MEMBERSHIP_REWARDS_POINTS, SKYMILES, USD]
   * @return currency
  **/
  @ApiModelProperty(value = "type of currency. Possible values: [MEMBERSHIP_REWARDS_POINTS, SKYMILES, USD]")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Reward value(Integer value) {
    this.value = value;
    return this;
  }

   /**
   * Reward amount
   * @return value
  **/
  @ApiModelProperty(value = "Reward amount")
  public Integer getValue() {
    return value;
  }

  public void setValue(Integer value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Reward reward = (Reward) o;
    return Objects.equals(this.currency, reward.currency) &&
        Objects.equals(this.value, reward.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Reward {\n");
    
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

