swagger: '2.0'
info:
  description: The AMEX Default Offers API provides the capability for a Partner to request standard card offer(s) eligible to new prospects and existing card members. It provides an interface for third-party systems to integrate with American Express internal APIs. Default Offers API allows the ability for card offers to be configured for the Partner within the AMEX downstream system, as it retrieves the offers based on Partner Identification (External Entry Point). This illustrates the Default Offers API, providing the standard offers for AMEX Card Acquisition Partners.
  version: '1.0'
  title: Global Default Offers API
  contact:
    name: Amex
    email: DAPXServices@aexp.com
basePath: /
schemes:
  - https
paths:
  /acquisition/digital/v1/offers/cards/default_offers:
    get:
      summary: AMEX Acquisition API for identifying right default offers for the consumer
      description: The API will accept partner name as a query string from Partners, identify default offers for the prospect / customer
      operationId: fetchDefaultOffers
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: entry_point
          in: query
          description: The External Entry Point value to fetch the data.
          required: true
          type: string
        - name: product_code
          in: query
          description: The unique product code to fetch the data.
          required: false
          type: string
        - name: content-type
          in: header
          description: The content type header.
          required: true
          type: string
          default: application/json
        - name: Authorization
          in: header
          description: The authorization header.
          required: true
          type: string
          default: Bearer <access_token value from Generate access token call above>
        - name: X-AMEX-API-KEY
          in: header
          description: The Apigee API Key.
          required: true
          type: string
          default: <Provided by AMEX Apigee>
        - name: message_type_id
          in: header
          description: The type of request.
          required: true
          type: string
        - name: request_timestamp
          in: header
          description: The request timestamp.
          required: false
          type: string
        - name: request_id
          in: header
          description: The unique request ID identifies the request for tracking.
          required: true
          type: string
        - name: client_id
          in: header
          description: The unique Client ID identifies the Client for tracking.
          required: true
          type: string
        - name: country_code
          in: header
          description: Specifies the country code. The format is based on the ISO 3166 two-letter (alpha-2) Country Codes. e.g., GB, US
          required: true
          type: string

      responses:
        '200':
          description: Successfully processed the request. [code:0 userMessage:Successfully processed the request.]
          schema:
            $ref: '#/definitions/OffersResponse'
          headers:
            response_timestamp:
              type: string
              description: The time stamp of the response.
            request_id:
              type: string
              description: The unique request ID supplied by the application to track the request.
            client_id:
              type: string
              description: The unique Client ID identifies the Client for tracking.
            content-length:
              type: string
              description: The response content length.
            content-type:
              type: string
              description: The response content type.
            api_elapsed_time:
              type: string
              description: The API elapsed time in milliseconds.
        '400':
          description: Bad request. Unrecoverable Error
          schema:
            $ref: '#/definitions/ErrorMessage'
          headers:
            response_timestamp:
              type: string
              description: The time stamp of the response.
            request_id:
              type: string
              description: The unique request ID supplied by the application to track the request.
            client_id:
              type: string
              description: The unique Client identifier identifies the Client for tracking.
            content-length:
              type: string
              description: The response content length.
            content-type:
              type: string
              description: The response content type.
            api_elapsed_time:
              type: string
              description: The API elapsed time in milliseconds.
        '404':
          description: Resource not found. Unrecoverable error.
        '500':
          description: Internal server error. Recoverable error please retry.
          schema:
            $ref: '#/definitions/ErrorMessage'
          headers:
            response_timestamp:
              type: string
              description: The time stamp of the response.
            request_id:
              type: string
              description: The unique request ID supplied by the application to track the request.
            client_id:
              type: string
              description: The unique Client identifier identifies the Client for tracking.
            content-length:
              type: string
              description: The response content length.
            content-type:
              type: string
              description: The response content type.
            api_elapsed_time:
              type: string
              description: The API elapsed time in milliseconds.

definitions:
  OffersResponse:
    type: object
    properties:
      refresh_interval:
        type: string
        description: The time to live for the token in milliseconds; the amount of time a token will remain valid.
      offers:
        type: array
        description: This holds a list of offers.
        items:
          $ref: '#/definitions/Offer'
  ErrorMessage:
    type: object
    properties:
      code:
        type: integer
        format: int32
        description: 'Error Code \nPossible values: \n\n1410: Errors related to request validation \n1420: Errors related to request parsing \n1440: Client specific repository errors \n1430: Client specific security errors \n1510: Offers API: API service errors \n1540: Offers API: API specific repository errors \n1530: Offers API: API specific security errors'
      user_message:
        type: string
        description: The user message.
      link:
        type: string
      developer_message:
        type: string
        description: The detailed message.
  Offer:
    type: object
    properties:
      acquisition_offer_id:
        type: string
        description: The unique offer identifier.
      line_of_business:
        type: string
        description: Indicates the line of business. e.g. CONSUMER OR SMALL_BUSINESS
      product_name:
        type: string
        description: The name of the product.
      product_type:
        type: string
        description: The type of the product. e.g. CHARGE or LENDING
      rewards:
        type: array
        items:
          $ref: '#/definitions/Reward'
        description: This holds the rewards information.
      urls:
        type: array
        items:
          $ref: '#/definitions/Url'
          description: This holds the URL information.
      fees:
        type: array
        items:
          $ref: '#/definitions/Fee'
        description: This holds any fee related to the product. e.g. annual fee of the product
      rates:
        type: array
        description: This holds an array of rates
        items:
          $ref: '#/definitions/Rate'
      content_groups:
        type: array
        description: This holds a list of content groups with contents related to the offer.
        items:
          $ref: '#/definitions/ContentGroup'
  Rate:
    type: object
    properties:
      name:
        type: string
        description: The name of the rates information. e.g. INTRODUCTORY_PURCHASE_APRREGULAR_PURCHASE_APRINTRODUCTORY_BALANCE_TRANSFER_APRREGULAR_BALANCE_TRANSFER_APRCASH_ADVANCE_APRPENALTY_APRPRIME_RATE
      value:
        type: string
        description: The APR value. e.g. 13.5%
      display_text:
        type: string
        description: The APR text to be displayed on the page. e.g. 0.0% for 15 months
      duration:
        type: string
        description: 'The duration of the applicable APR. e.g. 15 months'
    description: This model represents the rates information.
  Fee:
    type: object
    properties:
      name:
        type: string
        description: Represents the type of fee. e.g. INTORDUCTORY_ANNUAL_FEE, ANNUAL_FEE, NO_ANNUAL_FEE
      type:
        type: string
        description: 'Specifies the representation. e.g. FIXED, PERCENTAGE'
      value:
        type: string
        description: The fee amount. e.g. 95
      currency:
        type: string
        description: 'The type of currency. e.g. USD, RUPEE'
      display_text:
        type: string
        description: The text to be displayed on the page. e.g. $0 for the first year, then $195
    description: This holds the fee information.
  ContentGroup:
    type: object
    properties:
      name:
        type: string
        description: The name of the content group.
      contents:
        type: array
        description: This holds the contents grouped together related to the offer.
        items:
          $ref: '#/definitions/Content'
  Content:
    type: object
    properties:
      type:
        type: string
        description: The type of content. e.g. product or offer content
      title:
        type: string
        description: The headline for the content.
      disclosures:
        type: array
        description: The list of disclosures.
        items:
          $ref: '#/definitions/Disclosure'
      display_text:
        type: array
        description: The list of display text of the content.
        items:
          $ref: '#/definitions/DisplayText'
      sequence_order:
        type: integer
        format: int32
        description: The sequence of the content in the content group.
      image_url:
        type: string
        description: The URL of the image.
    description: This holds the offer/product content information.
  Url:
    type: object
    properties:
      name:
        type: string
        description: Specifies the name of the URL. e.g. APPLY, CARD_ART, TERMS_AND_CONDITIONS
      value:
        type: string
        description: The complete URL.
    description: Holds URL information.
  Disclosure:
    type: object
    properties:
      text:
        type: string
        description: The disclosure text to be displayed.
    description: Holds the card content disclosure.
  DisplayText:
    type: object
    properties:
      text:
        type: string
        description: The text to be displayed.
    description: Holds display text information.
  Reward:
    type: object
    properties:
      currency:
        type: string
        description: 'The type of currency. Possible values: MEMBERSHIP_REWARDS_POINTS, SKYMILES, USD'
      value:
        type: integer
        format: int32
        description: The reward amount.
    description: This represents the reward associated with the offer. Can be cashback or loyalty currency.
